# Generated by Django 4.1.5 on 2023-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsapp', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='key',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
