# Generated by Django 4.1.5 on 2023-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsapp', '0004_blog_email_blog_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
