# Generated by Django 4.1.5 on 2023-07-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newsapp', '0005_alter_blog_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Appuser',
        ),
    ]
